---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ k8s_node_ip }}" --apiserver-cert-extra-sans="{{ k8s_node_ip }}"  --node-name k8s-master --pod-network-cidr="{{k8s_cidr }}"

- name: Copy admin.conf to Home directory
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "/home/{{ k8s_user.name }}/.kube"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"
    mode: 0755
    remote_src: true

- name: Installing Reccomended Master Configuration
  get_url: 
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
    dest: "/home/{{ k8s_user.name }}/.kube/"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Installing Kubeconfig Template
  template:
    src: "{{ k8s_config }}"
    dest: "/home/{{ k8s_user.name }}/.kube/"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

