---
- name: Create Kubernetes config directory
  file:
    path: "/home/{{ k8s_user.name }}/.kube"
    state: directory
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Installing Reccomended Master Configuration
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
    dest: "/home/{{ k8s_user.name }}/.kube"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Installing Kubeconfig Template
  template:
    src: "{{ k8s_config }}.j2"
    dest: "/home/{{ k8s_user.name }}/.kube/{{ k8s_config }}"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"

- name: Initialize the Kubernetes cluster using kubeadm
  become_user: "{{ k8s_user.name }}"
  command: "sudo kubeadm init --apiserver-advertise-address={{ k8s_node_ip }} --apiserver-cert-extra-sans={{ k8s_node_ip }}  --node-name k8s-master --pod-network-cidr={{k8s_cidr }}"

- name: Setup kubeconfig
  copy:
    src: "{{ kubeadmin_config }}" 
    dest: "/home/{{ k8s_user.name }}/.kube/config"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"
    remote_src: yes

- name: Deploy kubernetes dashboard into cluster
  become_user: "{{ k8s_user.name }}"
  command: "kubectl --kubeconfig=/home/{{ k8s_user.name }}/.kube/config apply -f /home/{{ k8s_user.name }}/.kube/recommended.yaml" 

- name: Deploy latest version of calico chart inside calico-system namespace
  become_user: "{{ k8s_user.name }}"
  community.kubernetes.helm:
    name: calico
    chart_ref: https://github.com/projectcalico/calico/releases/download/v3.19.1/tigera-operator-v3.19.1-1.tgz
    release_namespace: calico-system
    create_namespace: yes

- name: Add ingress-nginx chart repo
  become_user: "{{ k8s_user.name }}"
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: HELM - Deploy latest version of Nginx chart inside monitoring namespace with values
  become_user: "{{ k8s_user.name }}"
  community.kubernetes.helm:
    name: nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: monitoring
    create_namespace: true

- name: Load kubernetes dashboard ingress 
  become_user: "{{ k8s_user.name }}"
  file:
    src: kubernetes_dashboard_ingress.yaml
    dest: /home/{{ k8s_user.name }}/.kube/kubernetes_dashboard_ingress.yaml

- name: Load kubernetes dashboard ingress 
  become_user: "{{ k8s_user.name }}"
  command: "kubectl apply -f /home/{{ k8s_user.name }}/.kube/kubernetes_dashboard_ingress.yaml" 

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: "copy content={{ join_command.stdout_lines[0] }} dest=./join-command"

