---
- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Installing Reccomended Master Configuration
  become_user: "{{ k8s_user.name }}" 
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
    dest: ".kube/"

- name: Installing Kubeconfig Template
  become_user: "{{ k8s_user.name }}" 
  template:
    src: "{{ k8s_config }}.j2"
    dest: ".kube/{{ k8s_config }}"

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ k8s_node_ip }}" --apiserver-cert-extra-sans="{{ k8s_node_ip }}"  --node-name k8s-master --pod-network-cidr="{{k8s_cidr }}"

- name: Setup kubeconfig for user "{{k8s_user.name }}"
  command: "{{ item }}"
    with_items:
      - mkdir -p /home/"{{k8s_user.name }}"/.kube
      - cp -i "{{ kubeadmin_config }}" /home/"{{k8s_user.name }}"/.kube/config
      - chown "{{k8s_user.name }}":"{{k8s_user.name }}" /home/"{{k8s_user.name }}"/.kube/config

- name: Install calico pod network
  become_user: "{{k8s_user.name" }}
  command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml 

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

