---

- name: "Configure node ip - {{ node_ip }}" 
  lineinfile:
    path: /etc/sysconfig/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }} 
  notify: 
      - 'restart kubelet'

- name: Fetch Helm Chart Manager for Kubernetes 
  get_url: 
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 
    dest: /tmp/helm.sh
    mode: 0755

- name: Installing Helm...
  become: false #interactive login shell required for helm.sh 
  shell: /tmp/helm.sh

- name: Create Kubernetes config directory
  file:
    path: "/home/{{ k8s_user.name }}/.kube/"
    state: directory
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Copy admin.conf to Home directory
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "/home/{{ k8s_user.name }}/.kube/config"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"
    mode: 0755
    remote_src: true

- name: Installing Reccomended Master Configuration
  get_url: 
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
    dest: "/home/{{ k8s_user.name }}/.kube/config"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"

- name: Installing Kubeconfig Template
  template:
    src: "{{ k8s_config }}"
    dest: "/home/{{ k8s_user.name }}/.kube/config"
    owner: "{{ k8s_user.name }}"
    group: "{{ k8s_user.group }}"
