---

- name: "Configure node ip - {{ node_ip }}" 
  lineinfile:
    path: /etc/sysconfig/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }} 
  notify: 
      - 'restart kubelet'

- name: Fetch Helm Chart Manager for Kubernetes 
  get_url: 
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 
    dest: /tmp/helm.sh
    mode: 0755

- name: Installing Helm...
  become: false #interactive login shell required for helm.sh 
  shell: /tmp/helm.sh
