# handlers file for k8s-master
---
- name: enable kubelet
  systemd:
    name: kubelet
    enabled: yes

- name: restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

