---

- name: "Configure node ip - {{ node_ip }}" 
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }} 
  notify: 
      - 'enable kubelet'
      - 'restart kubelet'

- name: Fetch Helm Chart Manager for Kubernetes 
  get_url: 
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 
    dest: /tmp/helm.sh
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: 0755

- name: Installing Helm...
  become_user: "{{ k8s_user }}"
  shell: /tmp/helm.sh
